Store.Web/ViewModels/RegisterGenreViewModel.cs
using DocumentFormat.OpenXml.Office2010.ExcelAc;
using Microsoft.Ajax.Utilities;
using Store.Model.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Text;

namespace Store.Web.ViewModels
{
    public class RegisterGenreViewModel
    {
        public string searching { get; set; }
        public int ID { get; set; }
        [Required(ErrorMessage = "გთხოვთ შეიყვანოთ ჟანრის დასახელება")]
        public string Name { get; set; }


    }
}

Store.Web/Controllers/GenreController.cs
using AutoMapper;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.Ajax.Utilities;
using Store.Data;
using Store.Data.Repositories;
using Store.Model;
using Store.Model.Models;
using Store.Service;
using Store.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace Store.Web.Controllers
{
    public class GenreController : Controller
    {
        private readonly IUsersService UsersService;
        private readonly IGenresService GenresService;
        private readonly IRolesService RolesService;
        private readonly IAuthorsService AuthorsService;
        private readonly IPositionsService PositionsService;
        private readonly StoreSeedData _seedData;
        private readonly IEmployeesService EmployeesService;



        public GenreController(IUsersService UsersService,IGenresService GenresService, IAuthorsService AuthorsService ,IPositionsService PositionsService ,IEmployeesService EmployeesService, IRolesService RolesService)
        {
            this.GenresService = GenresService;
            this.AuthorsService = AuthorsService;
            this.UsersService = UsersService;
            this.PositionsService = PositionsService;
            this.RolesService = RolesService;
            this.EmployeesService = EmployeesService;
            _seedData = new StoreSeedData();
        }
        public ActionResult Index()
        {
            var Genres = GenresService.GetGenres().ToList();
            return View(Genres);
        }


        [HttpGet]
        public ActionResult RegisterGenre()
        {
            return View();
        }

        [HttpPost]
        public ActionResult RegisterGenre(RegisterGenreViewModel model)
        {
            var allgenre = GenresService.GetGenres().ToList();
            foreach (var genr in allgenre)
            {
                if (model.Name == genr.Name)
                {
                    ModelState.AddModelError("UniqueGenre", "ასეთი ჟანრი უკვე არსებობს");
                }
            }
            if (ModelState.IsValid)
            {


                var genre = new Genres()
                {

                    Name = model.Name,
                    CreateDate = DateTime.Now,
                };
                GenresService.CreateGenre(genre);
                GenresService.SaveGenre();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public ActionResult View(int id)
        {
            var genre = GenresService.GetGenre(id);
            if (genre != null)
            {
                var viewModel = new RegisterGenreViewModel()
                {
                    Name = genre.Name,
                };

                return View("View", viewModel);
            }
            return View("Index");
        }
        [HttpPost]
        public ActionResult Submit(RegisterGenreViewModel model)
        {
            var allgenre = GenresService.GetGenres().ToList();
            foreach (var genr in allgenre)
            {
                if (model.Name == genr.Name)
                {
                    ModelState.AddModelError("UniqueGenre", "ასეთი ჟანრი უკვე არსებობს");
                }
            }
            if (ModelState.IsValid)
            {


                var genre = GenresService.GetGenre(model.ID);
                if (genre != null)
                {
                    //employee.ID = model.ID;
                    genre.Name = model.Name;
                    GenresService.SaveGenre();
                }
                return RedirectToAction("Index");
            }
            return View("View", model);
        }
        [HttpPost]
        public ActionResult Delete(RegisterGenreViewModel model)
        {
            var genre = GenresService.GetGenre(model.ID);
            if (genre != null)
            {

                GenresService.DeleteGenre(genre);
                GenresService.SaveGenre();

            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Search(string searching)
        {
            List<Genres> genresList = new List<Genres>();
            var genres = GenresService.GetGenres().ToList();
            foreach (var item in genres)
            {
                if (/*item.Name.StartsWith(searching)*/(item?.Name ?? null) != null && item.Name.StartsWith(searching) )
                {
                    genresList.Add(item);
                }
            }


            return View(genresList);

        }
    }
}

Store.Web/Views/Genre/Index.cshtml
@model List<Store.Model.Models.Genres>
@{
    ViewBag.Title = "Genres List";
}


    
    @using (Html.BeginForm("Search", "Genre", FormMethod.Get))
    {
        @Html.TextBox("searching")<input type="submit" value="Search" />

    }


<h3><a href="http://localhost:3523/Genre/RegisterGenre">Register new Genre</a></h3>
<h1>Genres</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var genre in Model)
        {
            <tr>
                <td>@genre.ID</td>
                <td>@genre.Name</td>
                <td><a href="http://localhost:3523/Genre/View/@genre.ID" class="btn btn-primary">View</a></td>


            </tr>
        }
    </tbody>
</table>

Store.Web/Views/Genre/RegisterGenre.cshtml
@model Store.Web.ViewModels.RegisterGenreViewModel
@{
    ViewBag.Title = "Register Genre";
}
<h2>Register Genre</h2>

@using (Html.BeginForm("RegisterGenre", "Genre", FormMethod.Post))
{

    <div class="form-group">
        <label>Name</label>
        <br />
        @Html.TextBoxFor(m => m.Name)
        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "attribute-error" })
        @Html.ValidationMessage("UniqueGenre", new { @class = "attribute-error" })

    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}
<style>
    .error-summary {
        color: red;
    }

    .attribute-error {
        display: block;
        color: red;
    }
</style>

Store.Web/Views/Genre/Search.cshtml
@model List<Store.Model.Models.Genres>
@{
    ViewBag.Title = "Search List";
}

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>

       
        @if(Model.Count() == 0)
            {
                <h1>no results</h1>
            }
        else {
        foreach (var genre in Model)
        {
            <tr>
                <td>@genre.ID</td>
                <td>@genre.Name</td>
                <td><a href="http://localhost:3523/Genre/View/@genre.ID" class="btn btn-primary">View</a></td>


            </tr>
        }
        }
    </tbody>
</table>

Store.Web/Views/Genre/View.cshtml
@model Store.Web.ViewModels.RegisterGenreViewModel

<h1>Edit Genre</h1>
@using (Html.BeginForm("Submit", "Genre", FormMethod.Post))
{
    <div class="form-group">
        <label>ID</label>
        <br />

        @Html.TextBoxFor(model => model.ID, new { value = Model.ID })

    </div>
    <div class="form-group">
        <label>Name</label>
        <br />

        @Html.TextBoxFor(model => model.Name, new { value = Model.Name })
        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "attribute-error" })
        @Html.ValidationMessage("UniqueGenre", new { @class = "attribute-error" })

    </div>
   

    <button type="submit" class="btn btn-primary">Submit</button>


    <button type="submit" class="btn btn-danger" formaction="@Url.Action("Delete", "Genre", new { id = Model.ID })">
        Delete
    </button>
}
<style>
    .error-summary {
        color: red;
    }

    .attribute-error {
        display: block;
        color: red;
    }
</style>