Store.Web/ViewModels/RegisterPublisherViewModel.cs
using DocumentFormat.OpenXml.Office2010.ExcelAc;
using Microsoft.Ajax.Utilities;
using Store.Model.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Text;

namespace Store.Web.ViewModels
{
    public class RegisterPublisherViewModel
    {
        public string searching { get; set; }
        public int ID { get; set; }
        [Required(ErrorMessage = "გთხოვთ შეიყვანოთ გამომცემელობის სახელი")]

        public string Name { get; set; }
        [Required(ErrorMessage = "გთხოვთ შეიყვანოთ გამომცემელობის მისამართი")]

        public string Address { get; set; }
        [Required(ErrorMessage = "გთხოვთ შეიყვანოთ გამომცემელობის ტელეფონის ნომერი")]

        public string PhoneNumber { get; set; }
        [Required(ErrorMessage = "გთხოვთ შეიყვანოთ გამომცემელობის მეილი")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "გთხოვთ მიუთითოთ სწორი ელ-ფოსტის მისამართი")]

        public string Email { get; set; }


    }
}

Store.Web/Controllers/PublisherController.cs
using AutoMapper;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.Ajax.Utilities;
using Store.Data;
using Store.Data.Repositories;
using Store.Model;
using Store.Model.Models;
using Store.Service;
using Store.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Runtime.Remoting.Messaging;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace Store.Web.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublishersService PublishersService;
        private readonly StoreSeedData _seedData;



        public PublisherController(IPublishersService PublishersService )
        {
            this.PublishersService = PublishersService;
            _seedData = new StoreSeedData();
        }
        public ActionResult Index()
        {
           var publishers = PublishersService.GetPublishers().ToList();
            return View(publishers);
        }


        [HttpGet]
        public ActionResult RegisterPublisher()
        {
            return View();
        }





        [HttpPost]
        public ActionResult RegisterPublisher(RegisterPublisherViewModel model)
        {
            var allpublisher = PublishersService.GetPublishers().ToList();
            foreach (var publisher in allpublisher)
            {
                if (model.Name == publisher.Name && model.Address == publisher.Address && model.PhoneNumber == publisher.PhoneNumber && model.Email == publisher.Email)
                {
                    ModelState.AddModelError("UniquePublisher", "ასეთი გამომცემლობა უკვე არსებობს");
                }
            }
            if (ModelState.IsValid)
            {


                var publisher = new Publishers()
                {

                    Name = model.Name,
                    Address = model.Address,
                    PhoneNumber = model.PhoneNumber,
                    Email = model.Email,
                    CreateDate = DateTime.Now,

                };
                PublishersService.CreatePublisher(publisher);
                PublishersService.SavePublisher();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult View(int id)
        {
            var publisher = PublishersService.GetPublisher(id);
            if (publisher != null)
            {
                var viewModel = new RegisterPublisherViewModel()
                {
                    Name = publisher.Name,
                    Address = publisher.Address,
                    PhoneNumber = publisher.PhoneNumber,
                    Email = publisher.Email,
                    
                };

                return View("View", viewModel);
            }
            return View("Index");
        }
        [HttpPost]
        public ActionResult Submit(RegisterPublisherViewModel model)
        {
             var allpublisher = PublishersService.GetPublishers().ToList();
            foreach (var publisher in allpublisher)
            {
                if (model.Name == publisher.Name && model.Address == publisher.Address && model.PhoneNumber == publisher.PhoneNumber && model.Email == publisher.Email)
                {
                    ModelState.AddModelError("UniquePublisher", "ასეთი გამომცემლობა უკვე არსებობს");
                }
            }
            var Publisher = PublishersService.GetPublisher(model.ID);
            if (ModelState.IsValid)
            {


                if (Publisher != null)
                {
                    Publisher.Name = model.Name;
                    Publisher.Address = model.Address;
                    Publisher.PhoneNumber = model.PhoneNumber;
                    Publisher.Email = model.Email;
                    PublishersService.SavePublisher();
                }
                return RedirectToAction("Index");
            }
            return View("View", model);
        }
        [HttpPost]
        public ActionResult Delete(RegisterPublisherViewModel model)
        {
            var publisher = PublishersService.GetPublisher(model.ID);
            if (publisher != null)
            {

                PublishersService.DeletePublisher(publisher);
                PublishersService.SavePublisher();

            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Search(string searching)
        {
            List<Publishers> publishersList = new List<Publishers>();
            var publishers = PublishersService.GetPublishers().ToList();
            foreach (var item in publishers)
            {
                if ((item?.Name ?? null) != null && item.Name.StartsWith(searching) || (item?.Address ?? null) != null && item.Address.StartsWith(searching) || (item?.PhoneNumber ?? null) != null && item.PhoneNumber.StartsWith(searching) || (item?.Email ?? null) != null && item.Email.StartsWith(searching))
                {
                    publishersList.Add(item);
                }
            }


            return View(publishersList);

        }
    }
}

Store.Web/Views/Publisher/Index.cshtml
@model List<Store.Model.Models.Publishers>
@{
    ViewBag.Title = "Publishers List";
}


    
    @using (Html.BeginForm("Search", "Publisher", FormMethod.Get))
    {
        @Html.TextBox("searching")<input type="submit" value="Search" />

    }


<h3><a href="http://localhost:3523/Publisher/RegisterPublisher">Register new Publisher</a></h3>
<h1>Publishers</h1>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>PhoneNumber</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>


        @foreach (var publisher in Model)
        {
            <tr>
                <td>@publisher.ID</td>
                <td>@publisher.Name</td>
                <td>@publisher.Address</td>
                <td>@publisher.PhoneNumber</td>
                <td>@publisher.Email</td>
                <td><a href="http://localhost:3523/Publisher/View/@publisher.ID" class="btn btn-primary">View</a></td>


            </tr>
        }
    </tbody>
</table>

Store.Web/Views/Publisher/RegisterPublisher.cshtml
@model Store.Web.ViewModels.RegisterPublisherViewModel
@{
    ViewBag.Title = "Register Publisher";
}
<h2>Register Publisher</h2>

@using (Html.BeginForm("RegisterPublisher", "Publisher", FormMethod.Post))
{

    <div class="form-group">
        <label>Name</label>
        <br />
        @Html.TextBoxFor(m => m.Name)
        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "attribute-error" })


    </div>
    <div class="form-group">
        <label>Address</label>
        <br />
        @Html.TextBoxFor(m => m.Address)
        @Html.ValidationMessageFor(m => m.Address, null, new { @class = "attribute-error" })


    </div>
    <div class="form-group">
        <label>PhoneNumber</label>
        <br />
        @Html.TextBoxFor(m => m.PhoneNumber)
        @Html.ValidationMessageFor(m => m.PhoneNumber, null, new { @class = "attribute-error" })


    </div>
    <div class="form-group">
        <label>Email</label>
        <br />
        @Html.TextBoxFor(m => m.Email)
        @Html.ValidationMessageFor(m => m.Email, null, new { @class = "attribute-error" })
        @Html.ValidationMessage("UniquePublisher", new { @class = "attribute-error" })



    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
}
<style>
    .error-summary {
        color: red;
    }

    .attribute-error {
        display: block;
        color: red;
    }
</style>

Store.Web/Views/Publisher/Search.cshtml
@model List<Store.Model.Models.Publishers>
@{
    ViewBag.Title = "Search List";
}

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
            <th>PhoneNumber</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>

       
        @if(Model.Count() == 0)
            {
                <h1>no results</h1>
            }
        else {
        foreach (var publisher in Model)
        {
            <tr>
                <td>@publisher.ID</td>
                <td>@publisher.Name</td>
                <td>@publisher.Address</td>
                <td>@publisher.PhoneNumber</td>
                <td>@publisher.Email</td>
                <td><a href="http://localhost:3523/Publisher/View/@publisher.ID" class="btn btn-primary">View</a></td>


            </tr>
        }
        }
    </tbody>
</table>

Store.Web/Views/Publisher/View.cshtml
@model Store.Web.ViewModels.RegisterPublisherViewModel

<h1>Edit Publisher</h1>
@using (Html.BeginForm("Submit", "Publisher", FormMethod.Post))
{
    <div class="form-group">
        <label>ID</label>
        <br />

        @Html.TextBoxFor(model => model.ID, new { value = Model.ID })

    </div>
    <div class="form-group">
        <label>Name</label>
        <br />

        @Html.TextBoxFor(model => model.Name, new { value = Model.Name })
        @Html.ValidationMessageFor(m => m.Name, null, new { @class = "attribute-error" })


    </div>
    <div class="form-group">
        <label>Address</label>
        <br />

        @Html.TextBoxFor(model => model.Address, new { value = Model.Address })
        @Html.ValidationMessageFor(m => m.Address, null, new { @class = "attribute-error" })


    </div>
    <div class="form-group">
        <label>PhoneNumber</label>
        <br />

        @Html.TextBoxFor(model => model.PhoneNumber, new { value = Model.PhoneNumber })
        @Html.ValidationMessageFor(m => m.PhoneNumber, null, new { @class = "attribute-error" })

    </div>
    <div class="form-group">
        <label>Email</label>
        <br />

        @Html.TextBoxFor(model => model.Email, new { value = Model.Email })
        @Html.ValidationMessageFor(m => m.Email, null, new { @class = "attribute-error" })
        @Html.ValidationMessage("UniquePublisher", new { @class = "attribute-error" })


    </div>

    <button type="submit" class="btn btn-primary">Submit</button>


    <button type="submit" class="btn btn-danger" formaction="@Url.Action("Delete", "Publisher", new { id = Model.ID })">
        Delete
    </button>
}
<style>
    .error-summary {
        color: red;
    }

    .attribute-error {
        display: block;
        color: red;
    }
</style>